name: CD pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check repository
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cun36nbtq21c73fgmo30?key=uylyFFcmTEU"
